#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    uses: Apodini/.github/.github/workflows/build-and-test.yml@main
    with:
      packagename: ApodiniTemplate
