#                   
# This source file is part of the Apodini open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Generate Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    name: Generate Docs
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Generate Docs
      run: |
          xcodebuild docbuild -scheme ApodiniTemplate -destination platform=macOS,arch=x86_64 -derivedDataPath ./.xcodebuild
          cp -r $(find ./.xcodebuild -type d -name '*.doccarchive') ./ApodiniTemplate.doccarchive
          echo "The DocC archive can be found at ./ApodiniTemplate.doccarchive"
    - name: Create Static HTML pages
      run: |
          git clone https://github.com/DoccZz/docc2html.git
          cd docc2html
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
          swift run docc2html ../ApodiniTemplate.doccarchive ../docs
          echo '<!DOCTYPE HTML>
          <html lang="en-US">
            <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=./documentation/apodinitemplate/apodinitemplate/index.html">
              <script type="text/javascript">
                window.location.href = "./documentation/apodinitemplate/apodinitemplate/index.html"
              </script>
              <title>Documentatoin</title>
            </head>
            <body>
              If you are not redirected automatically, follow this <a href='./documentation/apodinitemplate/apodinitemplate/index.html'>link to the documentation</a>.
            </body>
          </html>' > ../docs/index.html
    - name: Deploy to GH Pages
      uses: s0/git-publish-subdir-action@v2
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}