#                   
# This source file is part of the Apodini open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Generate Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    name: Generate Docs
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: pschmiedmayer/docc2html@main
      with:
        scheme: ApodiniTemplate
